# Generated by Django 4.2.4 on 2023-11-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0003_remove_label_task"),
        ("tasks", "0002_task_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(to="labels.label"),
        ),
    ]
